server:
  port: 9000
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: xbank-payment-service
  cloud:
    consul:
      host: localhost
      discovery:
        enabled: true
        register: true
        ipAddress: 127.0.0.1
        prefer-ip-address: true
        tags: local
        defaultQueryTag: local
        query-passing: true
        instance-id: ${spring.application.name}:${server.port}:local:${random.value}
        heartbeat:
          enabled: true
          ttl-value: 10